const fs=require('fs'),vm=require('vm');
function node(){return {classList:{add(){},remove(){},toggle(){}},style:{},dataset:{},addEventListener(){},removeEventListener(){},setAttribute(){},getAttribute(){return null},querySelector(){return null},querySelectorAll(){return []},appendChild(){},append(){},remove(){},insertAdjacentHTML(){},focus(){},click(){},getContext(){return null},getBoundingClientRect(){return {width:800,height:600,left:0,top:0}},children:[],options:[],value:'',checked:false,textContent:'',innerHTML:'',hidden:false};}
const _nodes=new Map();const document={body:node(),head:node(),documentElement:node(),getElementById(id){if(!_nodes.has(id))_nodes.set(id,node());return _nodes.get(id)},querySelector(){return null},querySelectorAll(){return []},addEventListener(){},removeEventListener(){},createElement(){return node()},createElementNS(){return node()}};
const window={document,innerWidth:390,innerHeight:844,devicePixelRatio:2,addEventListener(){},removeEventListener(){},dispatchEvent(){},matchMedia(){return {matches:true,addEventListener(){}}},location:{href:'http://localhost/',origin:'http://localhost',pathname:'/'},navigator:{},setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:(f)=>0,cancelAnimationFrame(){}};window.window=window;window.self=window;
const context={window,document,navigator:window.navigator,location:window.location,localStorage:{getItem(){return null},setItem(){},removeItem(){}},sessionStorage:{getItem(){return null},setItem(){},removeItem(){}},console,Math,Date,JSON,Array,Object,String,Number,Boolean,RegExp,Map,Set,WeakMap,WeakSet,Promise,Uint8Array,Int32Array,Float32Array,TextEncoder,TextDecoder,Blob:global.Blob,URL:global.URL,Event:function(){},CustomEvent:function(){},Image:function(){},FileReader:function(){},DOMParser:function(){this.parseFromString=()=>({querySelector(){return null},querySelectorAll(){return []}})},XMLSerializer:function(){},crypto:global.crypto,performance:global.performance,structuredClone:global.structuredClone,setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:window.requestAnimationFrame,cancelAnimationFrame:window.cancelAnimationFrame,alert(){},confirm(){return true},prompt(){return null},fetch:async()=>({ok:false}),atob:global.atob,btoa:global.btoa};context.globalThis=context;
for(let i=0;i<3;i++)vm.runInNewContext(fs.readFileSync(`/mnt/data/v267merge/script${i}.js`,'utf8'),context,{filename:`script${i}.js`,timeout:20000});
const api=window.__cartoAudit267;if(!api)throw Error('v26.7 audit API missing');
const sys={name:'Test System',stars:[],worlds:[],position:{x:0,y:0,z:0},sectorPosition:{x:0,y:0,z:0},config:{seed:'AUDIT'},summary:{bodies:0},soi:{elements:[]}};
const sub={name:'Test Subsector',systems:[sys],position:{x:0,y:0,z:0},radius:10,config:{seed:'AUDIT'},summary:{stars:1,bodies:0}};
const root={name:'Audit Sector',config:{era:'30k',seed:'AUDIT',generationScale:'sector',segmentum:'Segmentum Solar'},subsectors:[sub],rogueSystems:[],features:[],engagements:[],links:[],summary:{subsectors:1,systems:1},span:50,volume:125000};
const launch=api.launcherHTML(root);
if(!launch.includes('Starting Fleet'))throw Error('launcher Starting Fleet absent');
if(!launch.includes('Craftworld World-Ship'))throw Error('launcher Craftworld absent');
if(!(launch.indexOf('Starting Fleet')>launch.indexOf('Player faction')&&launch.indexOf('Starting Fleet')<launch.indexOf('Starting system')))throw Error('launcher placement incorrect');
const factionKeys=['legion','mechanicum','ork','craftworld','necron','rangdan','militia','solar','knights','talons','darkcompliance','kroot','rakgol','xenos','human'];
const results=[];
for(const key of factionKeys){
 const fac={id:`F-${key}`,key,name:key,color:'#aaa',ai:false,settlements:[],fleets:[],taskForces:[],treasury:{supply:100,materiel:100,influence:100},command:10,maxCommand:10,research:100,tech:{tier:5}};
 const st={id:`S-${key}`,factionId:fac.id,systemId:'SUB1-SYS1',locationId:'world:W1',locationName:'Audit Settlement',locationKind:'World',status:'Active',foundedTurn:0,colony:{size:6,type:'Settlement',displayType:'Settlement',infrastructure:[],infrastructureLevels253:{},supportUpgrades:[],events:[],productivity:7,order:7,complacency:7,piety:7}};fac.settlements=[st];
 root.campaign={playerFactionId:fac.id,factions:[fac],systems:{'SUB1-SYS1':{ownerFactionId:fac.id,presenceFactionIds:[fac.id],defence:0}},turn:0,seed:'AUDIT',selectedSystemId:'SUB1-SYS1'};window.currentSector=root;
 const a=api.audit(root,fac,st);
 if(key==='legion'){console.error('LEGION PLANNER',a.plannerHTML.slice(0,1800));console.error('LEGION PALETTE',a.paletteHTML.slice(0,1800));}
 results.push({key,infra:a.uniqueInfrastructureCount,allInfra:a.uniqueInfrastructureAllInDropdown,effects:a.uniqueInfrastructureEffectsVisible,districtVisible:a.uniqueDistrictVisible,districtFirst:a.uniqueDistrictFirst,plannerUnique:(a.plannerHTML.match(/FACTION UNIQUE/g)||[]).length,paletteIndex:a.paletteHTML.indexOf(`data-chain=\"${a.uniqueDistrictKey}\"`),musterIndex:a.paletteHTML.indexOf('Muster & Recruitment')});
}
console.log(JSON.stringify({ok:true,launcher:{startingFleet:true,craftworld:true,position:true},factions:results,revision:api.version,build:api.build},null,2));
