const fs=require('fs'),vm=require('vm');
function node(){return {classList:{add(){},remove(){},toggle(){}},style:{},dataset:{},addEventListener(){},removeEventListener(){},setAttribute(){},getAttribute(){return null},querySelector(){return null},querySelectorAll(){return []},appendChild(){},append(){},remove(){},insertAdjacentHTML(){},focus(){},click(){},getContext(){return null},getBoundingClientRect(){return {width:800,height:600,left:0,top:0}},children:[],options:[],value:'',checked:false,textContent:'',innerHTML:'',hidden:false};}
const _nodes=new Map();
const document={body:node(),head:node(),documentElement:node(),getElementById(id){if(!_nodes.has(id))_nodes.set(id,node());return _nodes.get(id)},querySelector(){return null},querySelectorAll(){return []},addEventListener(){},removeEventListener(){},createElement(){return node()},createElementNS(){return node()}};
const window={document,innerWidth:1200,innerHeight:800,devicePixelRatio:1,addEventListener(){},removeEventListener(){},dispatchEvent(){},matchMedia(){return {matches:false,addEventListener(){}}},location:{href:'http://localhost/',origin:'http://localhost',pathname:'/'},navigator:{},setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:(f)=>0,cancelAnimationFrame(){}};
window.window=window;window.self=window;
const context={window,document,navigator:window.navigator,location:window.location,localStorage:{getItem(){return null},setItem(){},removeItem(){}},sessionStorage:{getItem(){return null},setItem(){},removeItem(){}},console,Math,Date,JSON,Array,Object,String,Number,Boolean,RegExp,Map,Set,WeakMap,WeakSet,Promise,Uint8Array,Int32Array,Float32Array,TextEncoder,TextDecoder,Blob:global.Blob,URL:global.URL,Event:function(){},CustomEvent:function(){},Image:function(){},FileReader:function(){},DOMParser:function(){this.parseFromString=()=>({querySelector(){return null},querySelectorAll(){return []}})},XMLSerializer:function(){},crypto:global.crypto,performance:global.performance,structuredClone:global.structuredClone,setTimeout,clearTimeout,setInterval,clearInterval,requestAnimationFrame:window.requestAnimationFrame,cancelAnimationFrame:window.cancelAnimationFrame,alert(){},confirm(){return true},prompt(){return null},fetch:async()=>({ok:false}),atob:global.atob,btoa:global.btoa};context.globalThis=context;
for(let i=0;i<3;i++){
 try{vm.runInNewContext(fs.readFileSync(`/mnt/data/v267merge/script${i}.js`,'utf8'),context,{filename:`script${i}.js`,timeout:15000});console.log('SCRIPT',i,'OK');}
 catch(e){console.error('SCRIPT',i,'ERROR',e.stack);break}
}
console.log('REV266',!!context.window.__cartoRevision266,context.window.__cartoRevision266&&context.window.__cartoRevision266.build);
